name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t shiv2025/chatify-pro  .
      - name: Publish Image to docker hub
        run: docker push shiv2025/chatify-pro:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull shiv2025/chatify-pro:latest 
      - name: Delete old container
        run: docker rm -f chatify-pro-container  
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name chatify-pro-container -e MONGO_DB_URI='${{ secrets.MONGO_DB_URI }}' shiv2025/chatify-pro